### ISSUE TITLE
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00000000010180>

### ISSUE THREAD

**Issue by jkeen** [chaskiq/plain#7]
I'd love to try this gem out as it looks extremely helpful. I'm running Rails 7.1 + ruby 3.2, and the following error gets thrown when trying to load the app (`rails plain:load`, or just starting it up)

```NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00000000010180> (NoMethodError)```

**Comment by michelson** [comment]
can you show a more extensive trace log?

**Comment by jkeen** [comment]
```
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00000000010180> (NoMethodError)
Did you mean?  asset_host
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie/configuration.rb:109:in `method_missing'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/plain-rails-0.2.0/lib/plain/engine.rb:13:in `block in <class:Engine>'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `instance_exec'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `run'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:60:in `run_initializers'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:423:in `initialize!'
/Users/jeff/src/dt/api/config/environment.rb:9:in `<main>'
<internal:/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:399:in `require_environment!'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:571:in `block in run_tasks_blocks'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/sentry-ruby-5.12.0/lib/sentry/rake.rb:24:in `execute'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:241:in `each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:156:in `invoke_rake'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:73:in `block in invoke'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:149:in `with_argv'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:69:in `invoke'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands.rb:18:in `<main>'
<internal:/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => plain:load => environment
```

**Comment by michelson** [comment]
hi, what's the bundling system in your application? are you using propshaft
or sprockets?

the error tells me that this exception might be on the engine.rb of the
plain gem, were we call for app.config.assets.precompile += %w[
plain_manifest]

**Comment by jkeen** [comment]
Ah, I didn't have any sort of bundling set up because it's an api-only application. Does it work with import maps or do I need to get sprockets back in? It's been a minute since I've worked in the view layer of rails

**Comment by jkeen** [comment]
Had to add tailwindcss-rails to my gemfile in order for the styles to show up correctly. Now that everything is loading, I'm getting this other exception. I think `.to_h` was maybe removed from ActiveModel?

```
worker | 2023-10-31T22:16:05.166Z pid=71568 tid=2eg0 class=Plain::MessageProcessorJob jid=67f54a7d9d986c5ff35c5dd3 ERROR: Error performing Plain::MessageProcessorJob (Job ID: ca6ad0c4-f238-4ba6-b2d4-18c7f4536e95) from Sidekiq(default) in 1138.75ms: NoMethodError (undefined method `to_h' for #<Plain::Message id: 1, role: "user", content: "I'd like to change the default url of the asset pi...", plain_conversation_id: 1, created_at: "2023-10-31 20:46:58.555928000 +0000", updated_at: "2023-10-31 20:46:58.555928000 +0000">):
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activemodel-7.1.1/lib/active_model/attribute_methods.rb:489:in `method_missing'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.6.19/lib/langchain/conversation.rb:87:in `map'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.6.19/lib/langchain/conversation.rb:87:in `llm_response'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.6.19/lib/langchain/conversation.rb:61:in `message'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/plain-rails-0.2.0/app/services/plain/ai_docs.rb:73:in `set_conversation_title'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/plain-rails-0.2.0/app/models/plain/conversation.rb:33:in `add_assistant_response'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/plain-rails-0.2.0/app/jobs/plain/message_processor_job.rb:6:in `perform'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/execution.rb:69:in `block in _perform_job'
worker | /Users/jeff/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
```

**Comment by jkeen** [comment]
I had to add tailwindcss-rails in order to get things functioning and am now running into processing errors where it's failing on .to_h in Sidekiq, but it might be one of the sidekiq plugins. Thanks for the pointer to resolve the previous issue
